### Get All Gebruikers
GET http://localhost:4004/odata/v4/overview/Gebruikers

### Get Gebruiker By Id (1)
GET http://localhost:4004/odata/v4/overview/Gebruikers/1

### Get Gebruiker By Id + alle inschrijvingen
GET http://localhost:4004/odata/v4/overview/Gebruikers/3?$expand=*

###

GET http://localhost:4004/odata/v4/overview/Evenementen/1?$expand=*

### POST Gebruiker
POST http://localhost:4004/odata/v2/overview/Gebruikers
Content-Type: application/json

{
    "achternaam": "test",
    "email": "tom@gmail.com",
    "geboortedatum": "2024-04-05",
    "voornaam": "tom",
    "wachtwoord": "test"
}

### POST Evenement
POST http://localhost:4004/odata/v2/overview/Evenementen
Content-Type: application/json

{
    "eindDatum": "2024-04-26",
    "eindUur": "21:34",
    "locatie": "Event",
    "maxAantalInschrijvingen": "40",
    "naam": "Test",
    "prijs": "30",
    "beginDatum": "2024-04-26",
    "beginUur": "20:34"
}

### POST Sessie
POST http://localhost:4004/odata/v2/overview/Sessies
Content-Type: application/json

{
    "naam":"Test",
    "datum":"2024-04-26",
    "beginUur":"20:34",
    "eindUur":"21:34",
    "spreker":"Test",
    "korteInhoud":"Test",
    "evenement": {
        "evenementID": 1
    }
}

### POST Inschrijving
POST http://localhost:4004/odata/v2/overview/Inschrijvingen
Content-Type: application/json

{
    "gebruikerID": {
        "gebruikerID": "5379ef91-b23a-436b-92a0-ddeb4b48c0ca"
    },
    "sessieID": {
        "sessieID": 1
    }
}

### DELETE Inschrijving by GebruikerId and SessieId
DELETE http://localhost:4004/odata/v2/overview/Inschrijvingen(gebruikerID_gebruikerID=21,sessieID_sessieID=1)
### PUT Evenement
PUT http://localhost:4004/odata/v2/overview/Evenementen/1
Content-Type: application/json

{
    "eindDatum": "2024-04-26",
    "eindUur": "21:34",
    "locatie": "Event",
    "maxAantalInschrijvingen": 40,
    "naam": "Test",
    "prijs": 30,
    "beginDatum": "2024-04-26",
    "beginUur": "20:34"
}
